# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0e0456d72dc516f66c6e048aa102cd0bc60486bea3393c9afd7032e29e6d96030e73f1501bed9a5de46c573c327f07b8f3f0919f10b2aed836b5a3ddba0314

test:
  secret_key_base: abf5d6cd67c9d6c27e6257c81e2f93868bc60ef89c0f92fee99e1e9a7456e2217772db0e06d5dc575825f846c04749310af9cebffa28b14733cc4cc72c175260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
